# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
torch.rand((7,7))

tensor([[6.8365e-01, 8.7995e-02, 8.7682e-01, 9.8217e-02, 1.8123e-01, 5.1484e-01,
         6.2330e-01],
        [4.3153e-01, 5.0900e-01, 5.9729e-01, 2.5193e-01, 1.9730e-01, 9.6771e-01,
         6.7182e-01],
        [2.7442e-01, 1.6419e-01, 7.1985e-04, 5.6042e-01, 2.3959e-01, 3.9755e-01,
         6.4598e-01],
        [9.2043e-01, 6.7222e-01, 2.8074e-01, 3.1601e-01, 2.4865e-01, 3.5946e-01,
         8.1339e-01],
        [4.7805e-01, 4.4447e-01, 1.6254e-01, 2.2416e-02, 5.5445e-01, 9.3415e-01,
         7.5519e-01],
        [1.0536e-01, 2.3413e-01, 2.2779e-01, 1.0495e-01, 3.7784e-01, 8.3052e-01,
         3.2404e-01],
        [1.1514e-02, 3.7094e-01, 1.5382e-01, 8.2114e-01, 1.4957e-01, 3.3999e-01,
         3.7615e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor
x = torch.rand(size=(7, 7))
y = torch.rand(size=(1, 7))
# Perform matrix multiplication 
mull = x * y.T # TODO: element-wise multiplication
print(mull.shape)
mull = x @ y.T #TODO: matrix multiplication
print(mull.shape)
print(torch.matmul(x, y.T).shape)

torch.Size([7, 7])
torch.Size([7, 1])
torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(size = (7, 7))
tensor2 = torch.rand(size = (1, 7))

# Matrix multiply tensors
print(tensor1 @ tensor2.T)
print(torch.matmul(tensor1, tensor2.T))

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [14]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

# Create two random tensors on GPU
x = torch.rand(size = (2, 3)).to(device)
y = torch.rand(size = (2, 3)).to(device)
x, y

cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [25]:
# Perform matmul on tensor_A and tensor_B
maul = x @ y.T
maul, maul.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [27]:
# Find max
print(maul.max())

# Find min
print(maul.min())

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max
print(maul.argmax())
# Find arg min
print(maul.argmin())

tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [33]:
# Set seed
torch.manual_seed(7)

# Create random tensor
torch4d = torch.rand(size=(1,1,1,10))
torch4d
# Remove single dimensions
torch1d = torch4d.squeeze() 

# Print out tensors and their shapes
torch4d, torch4d.shape, torch1d, torch1d.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))